using System.ComponentModel;
using System.Text;
using System.Text.Json.Serialization;
using KoalaWiki.Core.DataAccess;

namespace KoalaWiki.Tools;

public class DocumentationTool(string warehouseId, IKoalaWikiContext dbContext)
{
    [KernelFunction(name: "ListDocs"),
     Description(
         """
         List all available documentation pages for this repository.
         Use this to discover what documentation has been generated and find relevant pages to read.
         Returns a list of documentation pages with their titles and URLs.
         """)]
    public async Task<string> ListDocumentationAsync()
    {
        var catalogs = await dbContext.DocumentCatalogs
            .AsNoTracking()
            .Where(x => x.WarehouseId == warehouseId && !x.IsDeleted && x.IsCompleted)
            .OrderBy(x => x.Order)
            .Select(x => new { x.Id, x.Name, x.Url, x.Description })
            .ToListAsync();

        if (catalogs.Count == 0)
        {
            return "No documentation pages found for this repository.";
        }

        var sb = new StringBuilder();
        sb.AppendLine("Available documentation pages:");
        sb.AppendLine();
        
        foreach (var catalog in catalogs)
        {
            sb.AppendLine($"- **{catalog.Name}** (URL: {catalog.Url})");
            if (!string.IsNullOrEmpty(catalog.Description))
            {
                sb.AppendLine($"  {catalog.Description}");
            }
        }

        return sb.ToString();
    }

    [KernelFunction(name: "ReadDoc"),
     Description(
         """
         Read the content of a specific documentation page.
         Use this to get the full generated documentation for a topic.
         The documentation contains analysis, explanations, and insights about the code that were generated by AI.
         
         Usage:
         - First use ListDocs to see available pages
         - Then use ReadDoc with the URL of the page you want to read
         - The URL should match exactly as shown in ListDocs output
         """)]
    public async Task<string> ReadDocumentationAsync(
        [Description("The documentation item to read. REQUIRED.")]
        ReadDocInput? item = null)
    {
        if (item == null || string.IsNullOrEmpty(item.Url))
        {
            return "<system-reminder>Error: URL is required. Use ListDocs first to see available documentation pages.</system-reminder>";
        }

        var catalog = await dbContext.DocumentCatalogs
            .AsNoTracking()
            .FirstOrDefaultAsync(x => x.WarehouseId == warehouseId && x.Url == item.Url && !x.IsDeleted);

        if (catalog == null)
        {
            return $"Documentation page not found: {item.Url}. Use ListDocs to see available pages.";
        }

        var fileItem = await dbContext.DocumentFileItems
            .AsNoTracking()
            .FirstOrDefaultAsync(x => x.DocumentCatalogId == catalog.Id);

        if (fileItem == null || string.IsNullOrEmpty(fileItem.Content))
        {
            return $"Documentation content is empty for: {item.Url}";
        }

        var sb = new StringBuilder();
        sb.AppendLine($"# {fileItem.Title}");
        sb.AppendLine();
        
        if (!string.IsNullOrEmpty(fileItem.Description))
        {
            sb.AppendLine($"*{fileItem.Description}*");
            sb.AppendLine();
        }
        
        sb.AppendLine(fileItem.Content);

        return sb.ToString();
    }

    [KernelFunction(name: "SearchDocs"),
     Description(
         """
         Search through documentation content for specific terms or topics.
         Returns matching documentation pages with relevant snippets.
         Use this when you need to find documentation about a specific topic.
         """)]
    public async Task<string> SearchDocumentationAsync(
        [Description("The search term to look for in documentation")]
        string searchTerm)
    {
        if (string.IsNullOrWhiteSpace(searchTerm))
        {
            return "<system-reminder>Error: searchTerm is required.</system-reminder>";
        }

        var searchLower = searchTerm.ToLower();

        var results = await dbContext.DocumentFileItems
            .AsNoTracking()
            .Include(x => x.I18nTranslations)
            .Where(x => dbContext.DocumentCatalogs
                .Any(c => c.Id == x.DocumentCatalogId && c.WarehouseId == warehouseId && !c.IsDeleted))
            .Where(x => x.Title.ToLower().Contains(searchLower) || 
                        x.Content.ToLower().Contains(searchLower) ||
                        x.Description.ToLower().Contains(searchLower))
            .Take(10)
            .ToListAsync();

        if (results.Count == 0)
        {
            return $"No documentation found matching: {searchTerm}";
        }

        var sb = new StringBuilder();
        sb.AppendLine($"Found {results.Count} documentation page(s) matching '{searchTerm}':");
        sb.AppendLine();

        foreach (var item in results)
        {
            var catalog = await dbContext.DocumentCatalogs
                .AsNoTracking()
                .FirstOrDefaultAsync(x => x.Id == item.DocumentCatalogId);

            sb.AppendLine($"### {item.Title}");
            if (catalog != null)
            {
                sb.AppendLine($"URL: {catalog.Url}");
            }
            
            var contentSnippet = GetSnippet(item.Content, searchLower, 200);
            if (!string.IsNullOrEmpty(contentSnippet))
            {
                sb.AppendLine($"```");
                sb.AppendLine(contentSnippet);
                sb.AppendLine($"```");
            }
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string GetSnippet(string content, string searchTerm, int contextLength)
    {
        if (string.IsNullOrEmpty(content))
            return string.Empty;

        var index = content.ToLower().IndexOf(searchTerm, StringComparison.Ordinal);
        if (index < 0)
            return content.Length > contextLength * 2 ? content[..(contextLength * 2)] + "..." : content;

        var start = Math.Max(0, index - contextLength);
        var end = Math.Min(content.Length, index + searchTerm.Length + contextLength);

        var snippet = content[start..end];
        
        if (start > 0) snippet = "..." + snippet;
        if (end < content.Length) snippet += "...";

        return snippet;
    }
}

public class ReadDocInput
{
    [Description("The URL of the documentation page to read (as shown by ListDocs)")]
    [JsonPropertyName("url")]
    public string Url { get; set; } = string.Empty;
}

